
name: Demo.NetFramework.CI

on: [push]
 
jobs:
  build:
    runs-on: windows-latest

    env:
      SLN_NAME: DemoSln.sln
      
    steps:
    - uses: actions/checkout@v1
    - name: Setup Nuget.exe
      uses: warrenbuckley/Setup-Nuget@v1
    - name: Restore packages
      run: nuget restore ${{ env.SLN_NAME }}
    - name: Setup MSBuild.exe
      uses: warrenbuckley/Setup-MSBuild@v1
    - name: Build with MSBuild
      run: msbuild  ${{ env.SLN_NAME }} -p:Configuration=Release
